sil_10_vitrine_homepage:
    path:     /
    defaults: { _controller: sil10VitrineBundle:Default:showName,name:visiteur }
    
_default:
    pattern: /accueil/{name}
    defaults: { _controller: sil10VitrineBundle:Default:showName,name:visiteur}
    
_mention:
    pattern: /mention
    defaults: { _controller: sil10VitrineBundle:Default:showMention}
    
_catalogue:
    pattern: /catalogue
    defaults: { _controller: sil10VitrineBundle:Default:showCatalogue}
    
_articlesParCategorie:
    pattern: /articlesParCategorie/{id}
    defaults: { _controller: sil10VitrineBundle:Default:showArticlesParCategorie}

_contenuPanier:
    pattern: /contenuPanier
    defaults: { _controller: sil10VitrineBundle:Panier:showContenuPanier}

_ajouteArticle:
    pattern: /panier/ajouteArticle/{idArticle}
    defaults: { _controller: sil10VitrineBundle:Panier:ajouteArticle}

_viderPanier:
    pattern: /panier/viderPanier/
    defaults: { _controller: sil10VitrineBundle:Panier:viderPanier}