# src/sil10/VitrineBundle/Ressources/config/doctrine/Article.orm.yml
sil10\VitrineBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        libelle:
            type: string
            lengh: 100
        prix:
            type: decimal
            scale: 2
        stock:
            type: integer
    manyToOne:
        categorie:
            targetEntity: Categorie
            inversedBy: articles
            joinColumn:
                name: categorie_id
                referenceColumnName: id
