# src/sil10/VitrineBundle/Ressources/config/doctrine/Client.orm.yml
sil10\VitrineBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom:
            type: string
            lengh: 100
        mail:
            type: string
            lengh: 100
    oneToMany:
        commandes:
            targetEntity: Commande
            mappedBy: client
        